# Molecular Search Pipeline Configuration

# Data paths
data:
  data_dir: "data"
  models_dir: "models"
  output_dir: "output"

# Model configuration
model:
  featurizer_type: "rdkit_2d"  # Options: "rdkit_2d"

# Database configuration
database:
  db_path: "molsearch.db"
  batch_size: 100

# Processing parameters
processing:
  batch_size: 10
  max_molecules: 1000
  n_jobs: -1  # Use all CPU cores
  progress_bar: true
  save_intermediate: false

# Logging
logging:
  level: "INFO"  # DEBUG, INFO, WARNING, ERROR
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
  file: "pipeline.log"

# Analysis parameters
analysis:
  tanimoto_threshold_high: 0.7
  tanimoto_threshold_medium: 0.5
  top_k_search: 100 